Move alff-push and alff-approve-rules to /usr/share/alff/routines/ as they are internal alff functions and should not be executables in /usr/sbin

diff --git a/bin/alff b/bin/alff
--- a/bin/alff
+++ b/bin/alff
@@ -205,8 +205,8 @@ case "$1" in
 		# Maybe we got an explicit machine to push to
 		if [ "${2}" ]; then
 			echo -n "Pushing ruleset to ${2}: "
-			alff-push "${2}" "${CURRENT_RULESET}" && echo "done." || echo "FAILED!"
-			alff-approve-rules "${2}"
+			exec_function push-rules "${2}" "${CURRENT_RULESET}" && echo "done." || echo "FAILED!"
+			exec_function approve-rules "${2}"
 		else
 			MACHINE_IDS=`alff getMachines`
 			if [ -z "${MACHINE_IDS}" ]; then
@@ -216,8 +216,8 @@ case "$1" in
 			
 			for machine_id in ${MACHINE_IDS}; do
 				echo -n "Pushing rules to ${machine_id}: "
-				alff-push ${machine_id} "${CURRENT_RULESET}" && echo "done." || echo "FAILED!"
-				alff-approve-rules "${machine_id}"
+				exec_function push ${machine_id} "${CURRENT_RULESET}" && echo "done." || echo "FAILED!"
+				exec_function approve-rules "${machine_id}"
 				echo ""
 			done
 		fi
