Added basic config space handling to the alff binary.
 From now on alff will know what config spaces are.
 You can now specify a config space (practically meaning a name of a
 directory in /etc/alff) where your alff configuration is stored.
 This allows you to manage multiple firewalls from one client.

Signed-off-by: Maximilian Wilhelm <max@rfc2324.org>

diff --git a/bin/alff b/bin/alff
--- a/bin/alff
+++ b/bin/alff
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/bin/sh
 #
 # alff
 #
@@ -8,42 +8,55 @@
 #  -- Thu, 08 Dec 2005 18:01:52 +0100
 #
 
-##
-# Configuration stuff
-CONFIG_FILE="/etc/alff/alff.conf"
-CONFIG_DIR="/etc/alff"
-PLUGIN_D="${CONFIG_DIR}/plugin.d"
+# Who I am
+MY_NAME="alff"
 
 ##
-# alf library stuff
+# alff library stuff
 export ALFF_FUNCTION_DIR="/usr/share/alff/routines/"
 PLUGIND_PLUGIN_DIR="/usr/share/alff/plugins/plugin.d/"
 
 ##
-# Some caches used at runtime
-CACHE_DIR="/var/cache/alff/"
-CACHE_DIR_BUILD="${CACHE_DIR}/ruleset.build"
-CACHE_DIR_CHAINS="${CACHE_DIR}/chains"
-CURRENT_RULESET="${CACHE_DIR}/alff.rules"
+# Some default values
+CONFIG_BASEDIR="/etc/alff"
 
-MY_NAME="alff"
+# The config space to use if none specified
+DEFAULT_CONFIG_SPACE="default"
 
 ## Some functions ##
 
 function checkConfigDir() { # Check the configuration (environment) #{{{
 	if [ ! -d "${CONFIG_DIR}" ]; then
+		usage
 		echo "Error: CONFIG_DIR \"${CONFIG_DIR}\" does not exist!" >&2
+
+		# define COMPAT
+		if [ "${CONFIG_SPACE}" = 'default' ]; then
+			echo "" >&2
+			echo "If you are upgrading from an earlier version of alff, please move your" >&2
+			echo "configuration from /etc/alff to ${CONFIG_BASEDIR}/${DEFAULT_CONFIG_SPACE}." >&2
+			echo "This will make your configuration to be the 'default' config space and" >&2
+			echo "you can use alff as before." >&2
+		fi
+		exit 1
+	fi
+
+	if [ ! -f "${CONFIG_FILE}" ]; then
+		echo "Error: There is no alff.conf in \"${CONFIG_DIR}\".">&2
 		exit 1
 	fi
 
 	if [ ! -d "${PLUGIN_D}" ]; then
+		usage
 		echo "Error: CONFIG_DIR \"${PLUGIN_D}\" does not exist!" >&2
 		exit 1
 	fi
+} #}}}
 
-	for dir in \. filter mangle nat; do
-		if [ ! -d "${CACHE_DIR_CHAINS}/${dir}" ]; then
-			mkdir -p "${CACHE_DIR_CHAINS}/${dir}"
+function initCacheDirs() { # Initialize the cache directories #{{{
+	for table in \. filter mangle nat raw; do
+		if [ ! -d "${CACHE_DIR_CHAINS}/${table}" ]; then
+			mkdir -p "${CACHE_DIR_CHAINS}/${table}"
 		fi
 	done
 
@@ -61,7 +74,7 @@ function checkTools() { # check for needed tooles #{{{
 } #}}}
 
 function usage() { # print usage #{{{
-	echo "Usage: ${MY_NAME} { generate | push | -list | <function> [ <param> ] }"
+	echo "Usage: ${MY_NAME} [ -c config_space ] { generate | push | -list | <function> [ <param> ] }"
 	echo ""
 	echo "${MY_NAME} is the main firewall management tool."
 	echo "It is used for generating rulesets, pushing rulesets to your firewalls"
@@ -69,6 +82,7 @@ function usage() { # print usage #{{{
 	echo "See 'alff -list' for a list of all available functions."
 	echo ""
 	echo "We assume that you know what you are doing..."
+	echo ""
 } #}}}
 
 function list_functions() { # list available functions #{{{
@@ -125,26 +139,73 @@ function preload()
 
 ## Showtime ##
 
+##
+# Check for config_space
+if [ "$1" = '-c' ]; then
+	CONFIG_SPACE="${2}"
+
+	# Dereference symlink if any
+	if [ -L "${CONFIG_BASEDIR}/${CONFIG_SPACE}" ]; then
+		CONFIG_SPACE=`readlink -e "${CONFIG_SPACE}"`
+	fi
+
+	# Check if this configspace exists
+	if [ -z "${CONFIG_SPACE}" -o ! -d  "${CONFIG_BASEDIR}/${CONFIG_SPACE}" ]; then
+		echo "ERROR: Config space \"${CONFIG_SPACE}\" does not exist." >&2
+		exit 1
+	fi
+
+	# OK should be valid
+	# Remove -c $CONFIG_SPACE from the command line parameters
+	shift 2
+else
+	CONFIG_SPACE="${DEFAULT_CONFIG_SPACE}"
+fi
+
+##
+# Configuration stuff
+export CONFIG_SPACE
+export CONFIG_DIR="${CONFIG_BASEDIR}/${CONFIG_SPACE}"
+export CONFIG_FILE="${CONFIG_DIR}/alff.conf"
+PLUGIN_D="${CONFIG_DIR}/plugin.d"
+
+##
+# Some caches used at runtime
+export CACHE_BASEDIR="/var/cache/alff/${CONFIG_SPACE}"
+export CACHE_DIR_BUILD="${CACHE_BASEDIR}/ruleset.build"
+export CACHE_DIR_CHAINS="${CACHE_BASEDIR}/chains"
+CURRENT_RULESET="${CACHE_BASEDIR}/alff.rules"
+
+
+
 checkConfigDir
 checkTools
+initCacheDirs
 
 preload "/usr/share/alff/lib/routines"
 
 case "$1" in 
-	-h|--help) #{{{
+	-c) # This should not happend with a valid command line. {{{
+		usage
+		exit 1
+		;;
+		#}}}
+
+	-h|--help) # Print usage text {{{
 		usage
 		exit 0
 		;;
 		#}}}
 
-	-list) #{{{
+	-list) # List available functions {{{
 		list_functions
 		exit 0
 		;;
 		#}}}
 
-	generate) #{{{
+	generate) # Generate ruleset {{{
 		echo "The ALFF Linux Firewall Framework awakes ..."
+		echo "Using config space ${CONFIG_SPACE}."
 		echo ""
 
 		echo -n  "Cleaning up cache dirs... "
@@ -167,7 +228,7 @@ case "$1" in
 
 		echo ""
 		echo ""
- 		configureFirewallNetworkOptions 3> "${CACHE_DIR_BUILD}/000_proc_options"
+		configureFirewallNetworkOptions 3> "${CACHE_DIR_BUILD}/000_proc_options"
 		echo ""
 
 		echo "Generating rules... "
@@ -208,8 +269,9 @@ case "$1" in
 		;;
 		#}}}
 
-	push) #{{{
+	push) # Push ruleset to firewall machine(s) {{{
 		echo "The ALFF Linux Firewall Framework awakes ..."
+		echo "Using config space ${CONFIG_SPACE}."
 		echo ""
 
 		if [ ! -s "${CURRENT_RULESET}" ]; then
@@ -250,7 +312,7 @@ case "$1" in
 		;;
 		#}}}
 
-	*) #{{{
+	*) # If $1 is a function, execute it {{{
 		if [ $# -gt 0 ]; then
 			# try to run former $1
 			exec_function ${@}
