Updated 'alff removeService' to be config space compliant and cleaned up the code.
Signed-off-by: Maximilian Wilhelm <max@rfc2324.org>

diff --git a/share/routines/removeService b/share/routines/removeService
--- a/share/routines/removeService
+++ b/share/routines/removeService
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/sh -e
 #
 # removeService <servicename>
 #
@@ -6,10 +6,10 @@
 #  -- Mon, 19 Dec 2005 14:01:30 +0100
 #
 
-set -e
+. /usr/share/alff/lib/routines
 
-SERVICES_D="/etc/alff/services.d"
-
+# Where the service configurations are stored.
+SERVICES_D="${ALFF_CONFIG_DIR}/services.d"
 
 if [ -z "${1}" ]; then
 	echo "Usage: $0 service" >&2
@@ -19,7 +19,6 @@ fi
 SERVICE="${1}"
 echo "alff: Removing service ${SERVICE}..."
 
-##
 # Check for service dir
 if [ ! -d "${SERVICES_D}" ]; then
 	echo "Error: services.d directory ${SERVICES_D} does not exists." >&2
@@ -32,4 +31,4 @@ if [ !  -f "${SERVICES_D}/${SERVICE}" ]; then
 fi
 
 echo -n " * Removing configuration for service ${SERVICE}... "
-rm "${SERVICES_D}/${SERVICE}" && echo "done." || echo "FAILED!"
+rm -- "${SERVICES_D}/${SERVICE}" && echo "done." || echo "FAILED!"
