Maexchen hat gewirkt[tm]

diff --git a/share/plugins/chain.d/accept_established_connections b/share/plugins/chain.d/accept_established_connections
--- a/share/plugins/chain.d/accept_established_connections
+++ b/share/plugins/chain.d/accept_established_connections
@@ -16,10 +16,10 @@
 # (Thanks to the munin if_ plugin coders for this idea)
 CHAIN=`basename $0 | awk -F_ '{ print $NF }'`
 
-if ${CHAIN}; then
+if [ "${CHAIN}" ]; then
 	echo -n " * Creating rule to ACCEPT established connections... "
 	iptables -A ${CHAIN} -m state --state RELATED,ESTABLISHED -j ACCEPT && echo "done." || echo "FAILED!"
 else
-	echo "Error: You did not specify the chain in which 'spoofcheck' should be hooked in" >&2
+	echo "Error: You did not specify the chain in which established connection should be hooked in" >&2
 fi
 
