alff-cat: If configured, include a diff of the ruleset in iptables-print format.

diff --git a/agent/alff-cat b/agent/alff-cat
--- a/agent/alff-cat
+++ b/agent/alff-cat
@@ -12,12 +12,13 @@
 # ATTENTION:
 # Do never ever add
 #       || echo "FAILED!"
-# anywhere in this tool, because we want 'set -e' do handle this case!!
+# anywhere in this tool, because we want 'set -e' to handle this case!!
 set -e
 
 export LOG_FILE=`tempfile`
 export ERROR_LOG=`tempfile`
 export MAIL_FILE=`tempfile`
+export RULES_DIFF=`tempfile`
 
 # Try to load configuration
 if [ -f /etc/alff/alff-agent.conf ]; then
@@ -78,6 +79,24 @@ function restore_old_rules() { #{{{
 	iptables-restore < "${OLD_RULES_FILE}" && echo "done."
 } #}}}
 
+# Save the current ruleset to $OLD_RULES_FILE and 
+# save a zeroed iptables output dump to $OLD_RULES_FILE.iptables
+function dump_current_rules() { #{{{
+
+	# Save rules in internal iptables format for case of restore
+	if ! iptables-save > "${OLD_RULES_FILE}"; then
+		return 1
+	fi
+
+	# Save rules in iptables-print-format for possible diff
+	echo > "${OLD_RULES_FILE}.iptables"
+	for table in ${DIFF_TABLES}; do
+		if ! iptables -t ${table} -Z -L -v -n | grep -v '^Zeroing chain' >> "${OLD_RULES_FILE}.iptables"; then	
+			return 1
+		fi
+	done
+} #}}}
+
 # Usage: send_mail { success, fail }
 function send_mail() { #{{{
 
@@ -115,6 +134,31 @@ The old rules have been restored."
 	
 	EOMAILHEADER
 
+	# Diff ruleset in iptables format for the admin #{{{
+	if [ "${1}" = 'success' -a "${DIFF_TABLES}" ]; then
+
+		echo > "${CURRENT_RULES_FILE}.iptables"
+		for table in ${DIFF_TABLES}; do
+			iptables -t ${table} -Z -L -v -n | grep -v '^Zeroing chain' >> "${CURRENT_RULES_FILE}.iptables"
+		done
+
+		diff -up "${OLD_RULES_FILE}.iptables" "${CURRENT_RULES_FILE}.iptables" > "${RULES_DIFF}"
+		if [ -s "${RULES_DIFF}" ]; then
+			# Diff of the ruleset
+			cat <<- EODIFF >> ${MAIL_FILE}"
+			
+			There are some differences:
+			================================================================================
+			EODIFF
+
+			cat "${RULES_DIFF}" >> "${MAIL_FILE}"
+
+			echo -e "==============================================================================\n" >> "${MAIL_FILE}"
+		else
+			echo -e "\n There are no differences in the rules. \n" >> "${MAIL_FILE}"
+		fi
+	fi #}}}
+
 	if [ -s "${LOG_FILE}" ]; then #{{{
 		cat <<- EOF >> "${MAIL_FILE}"
 	
@@ -122,7 +166,7 @@ The old rules have been restored."
 		==============================================================================
 		EOF
 		
-		cat < "${LOG_FILE}" >> "${MAIL_FILE}"
+		cat "${LOG_FILE}" >> "${MAIL_FILE}"
 	
 		echo -e "==============================================================================\n" >> "${MAIL_FILE}"
 	fi #}}}
@@ -134,7 +178,7 @@ The old rules have been restored."
 		==============================================================================
 		EOF
 		
-		cat < "${ERROR_LOG}" >> "${MAIL_FILE}"
+		cat "${ERROR_LOG}" >> "${MAIL_FILE}"
 		
 		echo -e "==============================================================================\n" >> "${MAIL_FILE}"
 	fi #}}}
@@ -148,9 +192,9 @@ The old rules have been restored."
 ##
 # Ok, let´s go
 
-# Save the current ruleset to $OLD_RULES_FILE
+# Dump old rules
 echo -n "1"
-if iptables-save > "${OLD_RULES_FILE}"; then
+if dump_current_rules; then
 	echo -n "."
 else
 	echo "FAILED to dump current ruleset!"
@@ -222,7 +266,7 @@ exec < /dev/null 1> "${LOG_FILE}" 2> "${ERROR_LOG}"
 		send_mail success
 	fi
 
-	rm "${LOG_FILE}" "${ERROR_LOG}" "${MAIL_FILE}"
+	rm "${LOG_FILE}" "${ERROR_LOG}" "${MAIL_FILE}" "${RULES_DIFF}"
 ) &
 	
 # vim:foldmethod=marker
