Some minor improvements for the alff-cat.
Signed-off-by: Maximilian Wilhelm <max@rfc2324.org>

diff --git a/agent/alff-cat b/agent/alff-cat
--- a/agent/alff-cat
+++ b/agent/alff-cat
@@ -57,7 +57,7 @@ fi
 
 # Check for some needed binaries
 for tool in tempfile iptables-save iptables-restore; do
-	if ! command -v ${tool} >/dev/null; then
+	if ! command -v "${tool}" >/dev/null; then
 		echo "Error: '${tool}' is required by ${MY_NAME}, but was not found!" >&2
 		exit 2
 	fi
@@ -79,7 +79,7 @@ function restore_old_rules() { #{{{
 	iptables-restore < "${OLD_RULES_FILE}" && echo "done."
 } #}}}
 
-function dump_tables() { # {
+function dump_tables() { # {{{
 	for table in ${DIFF_TABLES}; do
 		if ! iptables -t ${table} -L -v -n | sed -e 's/^[[:space:]]*[0-9]\+[KMG]\?[[:space:]]\+[0-9]\+[KMG]\?\(.*\)/    0     0\1/' \
 							-e 's/[0-9]\+[KMG]\? packets, [0-9]\+[KMG]\? bytes)/0 packets, 0 bytes)/' ; then	
@@ -103,7 +103,7 @@ function dump_current_rules() { #{{{
 	fi
 } #}}}
 
-# Usage: send_mail { success, fail }
+# Usage: send_mail { success, fail, token }
 function send_mail() { #{{{
 
 	# Maybe someone does alff-cat to shut up
@@ -166,7 +166,7 @@ The old rules have been restored."
 	if [ -s "${LOG_FILE}" ]; then #{{{
 		cat <<- EOF >> "${MAIL_FILE}"
 	
-		There's something in the logfile:
+		There's something in the logfile (catched from stdout):
 		==============================================================================
 		EOF
 		
@@ -178,7 +178,7 @@ The old rules have been restored."
 	if [ -s "${ERROR_LOG}" ]; then #{{{
 		cat <<- EOF >> "${MAIL_FILE}"
 		
-		There's something in the error log:
+		There's something in the error log (catched from stderr):
 		==============================================================================
 		EOF
 		
@@ -205,7 +205,7 @@ else
 	emergency_break
 fi
 
-# Save current rules to disk, to keep them over reboot
+# Save new rules to disk, to keep them over reboot
 echo -n " 2"
 if cat "${RULES_FILE}" > "${CURRENT_RULES_FILE}"; then
 	echo -n "."
@@ -230,6 +230,7 @@ else
 	exit 4
 fi
 
+echo -n " 4"
 if touch "${RULES_LOADING_TOKEN}"; then
 	echo -n "."
 else
@@ -244,7 +245,7 @@ else
 	exit 5
 fi
 
-#echo "Will now go to background an load new rules and wait ${SLEEP_TIME:-180} sec. for deletion of the token."
+#echo "Will now go to background and load new rules and wait ${SLEEP_TIME:-180} sec. for deletion of the token."
 echo -n " ..."
 
 exec < /dev/null 1> "${LOG_FILE}" 2> "${ERROR_LOG}"
@@ -260,6 +261,7 @@ exec < /dev/null 1> "${LOG_FILE}" 2> "${ERROR_LOG}"
 	fi
 
 	# Rule loading has finished.
+	# (If the rules did load successfull does not matter here!)
 	rm -- "${RULES_LOADING_TOKEN}"
 
 	# If the rules did load without error, try to get them approved
