Updated alff library routines to only try to execute the hooks if there are any.

diff --git a/share/lib/routines b/share/lib/routines
--- a/share/lib/routines
+++ b/share/lib/routines
@@ -46,10 +46,46 @@ function configureFirewallNetworkOptions() { # {{{
 # }}}
 
 ##
+# Check if there are hooks of the given type
+function hooksExist () { #{{{
+	local HOOK_TYPE="${1}"
+
+	case "${HOOK_TYPE}" in
+		pregenerate)		;;
+		postgenerate)		;;
+		prepush)		;;
+		postpush)		;;
+		*)
+			echo "Error: Invalid hooktype \"${HOOK_TYPE}\"" >&2
+			return 1
+			;;
+	esac
+
+	if [ -z "${CONFIG_DIR}" ]; then
+		CONFIG_DIR="/etc/alff"
+	fi
+
+	HOOK_DIR="${CONFIG_DIR}/hooks/${HOOK_TYPE}.d"
+	if [ ! -d "${HOOK_DIR}" ]; then
+		return 1
+	fi
+
+	if ! find "${HOOK_DIR}" \( -type f -or -type l \) | while read hook; do
+		if [ -x "${hook}" ]; then
+			exit 1
+		fi
+	done; then
+		return 0
+	else
+		return 1
+	fi
+} #}}}
+
+##
 # execute Hooks of given type
 function executeHooks() { #{{{
-	HOOK_TYPE="${1}"
-	
+	local HOOK_TYPE="${1}"
+
 	case "${HOOK_TYPE}" in
 		pregenerate)		;;
 		postgenerate)		;;
@@ -66,18 +102,17 @@ function executeHooks() { #{{{
 	fi
 	HOOK_DIR="${CONFIG_DIR}/hooks/${HOOK_TYPE}.d"
 
-	if [ -d "${HOOK_DIR}" ]; then
+	if hooksExist "${HOOK_TYPE}"; then
 		echo "Executing ${HOOK_TYPE} hooks..."
 		find "${HOOK_DIR}" \( -type f -or -type l \) -exec basename {} \; | sort -n | while read hook; do
 			if [ -x "${HOOK_DIR}/${hook}" ]; then
 				if ! sh -c "${HOOK_DIR}/${hook}"; then
-					echo "Error: ${HOOK_TYPE} hook \"${hook}\" exitet with status != 0" >&2
+					echo "Error: ${HOOK_TYPE} hook \"${hook}\" exited with status != 0" >&2
 					return 1
 				fi
 			fi
 		done
 	else
-#		echo "INFO: No hooks found for \"${HOOK_TYPE}\"" >&2
 		return 0 
 	fi
 } #}}}
