Updated 'routines' libary to be config space compliant.
Signed-off-by: Maximilian Wilhelm <max@rfc2324.org>

diff --git a/share/lib/routines b/share/lib/routines
--- a/share/lib/routines
+++ b/share/lib/routines
@@ -6,6 +6,19 @@
 #  -- Fri, 28 Apr 2006 19:52:22 +0200
 #
 
+if [ -z "${ALFF_CONFIG_DIR}" ]; then
+	echo "Error: $0 seems not to be run by alff." >&2
+	echo "If you think you know what you're doing you might want to" >&2
+	echo "  export ALFF_CONDIF_DIR=\"/etc/alff/<config_space>/\"" >&2
+	echo "or whereever you placed it." >&2
+	exit 1
+fi
+	
+if [ ! -d "${ALFF_CONFIG_DIR}" ]; then
+	echo "Error: ALFF_CONFIG_DIR ${ALFF_CONFIG_DIR} does not exist!" >&2
+	exit 1
+fi
+
 ##
 function configureFirewallNetworkOptions() { # {{{
 
@@ -61,11 +74,7 @@ function hooksExist () { #{{{
 			;;
 	esac
 
-	if [ -z "${CONFIG_DIR}" ]; then
-		CONFIG_DIR="/etc/alff"
-	fi
-
-	HOOK_DIR="${CONFIG_DIR}/hooks/${HOOK_TYPE}.d"
+	HOOK_DIR="${ALFF_CONFIG_DIR}/hooks/${HOOK_TYPE}.d"
 	if [ ! -d "${HOOK_DIR}" ]; then
 		return 1
 	fi
@@ -97,10 +106,7 @@ function executeHooks() { #{{{
 			;;
 	esac
 
-	if [ -z "${CONFIG_DIR}"  ]; then
-		CONFIG_DIR="/etc/alff"
-	fi
-	HOOK_DIR="${CONFIG_DIR}/hooks/${HOOK_TYPE}.d"
+	HOOK_DIR="${ALFF_CONFIG_DIR}/hooks/${HOOK_TYPE}.d"
 
 	if hooksExist "${HOOK_TYPE}"; then
 		echo "Executing ${HOOK_TYPE} hooks..."
